/**
 * Shared fixtures for RBAC tests.
 *
 * Provides a tiny `users` + `todos` schema, a fresh-DB factory, a seeded
 * cast of three users (two `user`-role, one `manager`), and context helpers.
 * Tests build their own RBAC config and pass it to `seed`.
 */
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";

import type { BuiltRbac } from "./rbac.js";

export const users = sqliteTable("users", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
});

export const todos = sqliteTable("todos", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  title: text("title").notNull(),
  ownerId: integer("owner_id").references(() => users.id),
});

export const allTables = { users, todos };

const createTablesSql = `
  CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL);
  CREATE TABLE todos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    owner_id INTEGER REFERENCES users(id)
  );
`;

export type Db = ReturnType<typeof drizzle>;

export function freshDb(): { sqlite: Database.Database; db: Db } {
  const sqlite = new Database(":memory:");
  sqlite.exec(createTablesSql);
  return { sqlite, db: drizzle(sqlite) };
}

export const ctxFor = (id: number, name = "u") => ({
  user: { id, name } as any,
  session: null,
  batch: new Map<string, unknown>(),
});

export const anonCtx = () => ({
  user: null,
  session: null,
  batch: new Map<string, unknown>(),
}) as any;

/**
 * Insert the canonical three-actor cast and their owned todos. Does NOT
 * assign roles — callers do that, since the role names vary by config.
 *
 *  - Alice owns alice-1 and alice-2
 *  - Bob   owns bob-1
 *  - Carol owns carol-1
 */
export async function insertCast(db: Db) {
  const [alice] = await db.insert(users).values({ name: "Alice" }).returning();
  const [bob]   = await db.insert(users).values({ name: "Bob" }).returning();
  const [carol] = await db.insert(users).values({ name: "Carol" }).returning();
  await db.insert(todos).values([
    { title: "alice-1", ownerId: alice.id },
    { title: "alice-2", ownerId: alice.id },
    { title: "bob-1",   ownerId: bob.id   },
    { title: "carol-1", ownerId: carol.id },
  ]);
  return { alice, bob, carol };
}

/** Cast where Alice + Bob are `user` and Carol is `manager`. */
export async function seedUserManager(db: Db, rbac: BuiltRbac) {
  const cast = await insertCast(db);
  rbac.assignRole(cast.alice.id, "user");
  rbac.assignRole(cast.bob.id,   "user");
  rbac.assignRole(cast.carol.id, "manager");
  return cast;
}

/** Cast where Alice is `reader`, Bob is `admin`, Carol has no role. */
export async function seedReaderAdmin(db: Db, rbac: BuiltRbac) {
  const cast = await insertCast(db);
  rbac.assignRole(cast.alice.id, "reader");
  rbac.assignRole(cast.bob.id,   "admin");
  // Carol intentionally unassigned — used as the no-role actor in deny tests.
  return cast;
}

/**
 * Sweep role memberships from process memory so a `beforeEach` can reset
 * cleanly between tests. The 1..1000 range comfortably covers the SQLite
 * autoincrement ids generated by `seedBaseCast` across a single test file.
 */
export function clearAllMemberships(rbac: BuiltRbac, max = 1000) {
  for (let id = 1; id < max; id++) {
    for (const key of rbac.listUserRoles(id)) rbac.revokeRole(id, key);
  }
}
